#Database Configuration
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserFiles
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: mongo-service

#Server
server:
  port: 8082
logging:
  level:
    by:
      dzikovskiy:
        postgresmicro: DEBUG

#Eurika and Spring admin
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
