#Database Configuration
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/users}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  application:
    name: local-grpc-server
  config:
    import: optional:configserver:http://localhost:8086
#  cloud:
#    config:
#      enabled: false
#Server
server:
  port: 8083
logging:
  level:
    by:
      dzikovskiy:
        postgresmicro: DEBUG
grpc:
  server:
    port: 9000
    address: '127.0.0.1'

#Eurika and Spring admin
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

text:
  copyright: Dev right (r)
