#Databases Configuration
host:
  url:
    mongo-db-microservice-host: http://localhost:8082/mongo
    postgres-microservice-host: http://localhost:8083/postgres

#Kafka configuration
kafka:
  usersTopic: USERS
  kafkaHost: 127.0.0.1:9092
#Server
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:users
  application:
    name: local-grpc-client

server:
  port: 8081
logging:
  level:
    by:
      dzikovskiy:
        usermicroservice: DEBUG
grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9000'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

#Eurika and Spring admin
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
