#Databases Configuration
host:
  url:
    mongo-db-microservice-host: http://localhost:8082/mongo
    postgres-microservice-host: http://localhost:8083/postgres

#Kafka configuration
kafka:
  usersTopic: USERS
  kafkaHost: 127.0.0.1:9092
#Server
spring:
  application:
    name: local-grpc-client
server:
  port: 8081
logging:
  level:
    by:
      dzikovskiy:
        postgresmicro: DEBUG
grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9000'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext