#App Configuration
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:users
  kafka:
    consumer:
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

#Kafka configuration
kafka:
  usersTopic: USERS
  kafkaHost: 127.0.0.1:9092

#Server
server:
  port: 8084
logging:
  level:
    by:
      dzikovskiy:
        kafkamicro: DEBUG