server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dzikovskiy/MicroservicesProperties.git
          clone-on-start: true
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: C:/Projects/Microservices/microservices/properties
#  profiles:
#    active: native